import { NetworkDeployment, SupportedNetwork } from "./interfaces/common";
import { activeContractsList } from "votera-contracts-lib";
import { Network } from "@ethersproject/networks";

export const LIVE_CONTRACTS: { [K in SupportedNetwork]: NetworkDeployment } = {
    [SupportedNetwork.MAINNET]: {
        IssuedContract: activeContractsList.mainnet.IssuedContract,
        AddressStorage: activeContractsList.mainnet.AddressStorage,
        BudgetManager: activeContractsList.mainnet.BudgetManager,
        ParamStorage: activeContractsList.mainnet.ParamStorage,
        ParticipantStorage: activeContractsList.mainnet.ParticipantStorage,
        EvaluatorStorage: activeContractsList.mainnet.EvaluatorStorage,
        ProposalStorage: activeContractsList.mainnet.ProposalStorage,
        AssessmentStorage: activeContractsList.mainnet.AssessmentStorage,
        VoteStorage: activeContractsList.mainnet.VoteStorage,
        ReceptionController: activeContractsList.mainnet.ReceptionController,
        AssessmentController: activeContractsList.mainnet.AssessmentController,
        VoteController: activeContractsList.mainnet.VoteController,
        ParticipantManager: activeContractsList.mainnet.ParticipantManager,
        EvaluatorManager: activeContractsList.mainnet.EvaluatorManager,
        ExecutionManager: activeContractsList.mainnet.ExecutionManager,
    },
    [SupportedNetwork.TESTNET]: {
        IssuedContract: activeContractsList.testnet.IssuedContract,
        AddressStorage: activeContractsList.testnet.AddressStorage,
        BudgetManager: activeContractsList.testnet.BudgetManager,
        ParamStorage: activeContractsList.testnet.ParamStorage,
        ParticipantStorage: activeContractsList.testnet.ParticipantStorage,
        EvaluatorStorage: activeContractsList.testnet.EvaluatorStorage,
        ProposalStorage: activeContractsList.testnet.ProposalStorage,
        AssessmentStorage: activeContractsList.testnet.AssessmentStorage,
        VoteStorage: activeContractsList.testnet.VoteStorage,
        ReceptionController: activeContractsList.testnet.ReceptionController,
        AssessmentController: activeContractsList.testnet.AssessmentController,
        VoteController: activeContractsList.testnet.VoteController,
        ParticipantManager: activeContractsList.testnet.ParticipantManager,
        EvaluatorManager: activeContractsList.testnet.EvaluatorManager,
        ExecutionManager: activeContractsList.testnet.ExecutionManager,
    },
    [SupportedNetwork.DEVNET]: {
        IssuedContract: activeContractsList.devnet.IssuedContract,
        AddressStorage: activeContractsList.devnet.AddressStorage,
        BudgetManager: activeContractsList.devnet.BudgetManager,
        ParamStorage: activeContractsList.devnet.ParamStorage,
        ParticipantStorage: activeContractsList.devnet.ParticipantStorage,
        EvaluatorStorage: activeContractsList.devnet.EvaluatorStorage,
        ProposalStorage: activeContractsList.devnet.ProposalStorage,
        AssessmentStorage: activeContractsList.devnet.AssessmentStorage,
        VoteStorage: activeContractsList.devnet.VoteStorage,
        ReceptionController: activeContractsList.devnet.ReceptionController,
        AssessmentController: activeContractsList.devnet.AssessmentController,
        VoteController: activeContractsList.devnet.VoteController,
        ParticipantManager: activeContractsList.devnet.ParticipantManager,
        EvaluatorManager: activeContractsList.devnet.EvaluatorManager,
        ExecutionManager: activeContractsList.devnet.ExecutionManager,
    },
    [SupportedNetwork.LOCAL]: {
        IssuedContract: activeContractsList.devnet.IssuedContract,
        AddressStorage: activeContractsList.devnet.AddressStorage,
        BudgetManager: activeContractsList.devnet.BudgetManager,
        ParamStorage: activeContractsList.devnet.ParamStorage,
        ParticipantStorage: activeContractsList.devnet.ParticipantStorage,
        EvaluatorStorage: activeContractsList.devnet.EvaluatorStorage,
        ProposalStorage: activeContractsList.devnet.ProposalStorage,
        AssessmentStorage: activeContractsList.devnet.AssessmentStorage,
        VoteStorage: activeContractsList.devnet.VoteStorage,
        ReceptionController: activeContractsList.devnet.ReceptionController,
        AssessmentController: activeContractsList.devnet.AssessmentController,
        VoteController: activeContractsList.devnet.VoteController,
        ParticipantManager: activeContractsList.devnet.ParticipantManager,
        EvaluatorManager: activeContractsList.devnet.EvaluatorManager,
        ExecutionManager: activeContractsList.devnet.ExecutionManager,
    },
};

export const ADDITIONAL_NETWORKS: Network[] = [
    {
        name: SupportedNetwork.MAINNET,
        chainId: 2151,
    },
    {
        name: SupportedNetwork.TESTNET,
        chainId: 2019,
    },
    {
        name: SupportedNetwork.DEVNET,
        chainId: 24680,
    },
];
